### ISSUE TITLE
Plugin doesn't work on Folia

### ISSUE THREAD

**Issue by roggy666** [ViaVersionAddons/AxSmithing#8]
![image](https://github.com/ViaVersionAddons/AxSmithing/assets/59109355/467a860e-7c5b-4b91-abb3-98b1b2cfa2cd)

[02:28:56 ERROR]: Could not pass event InventoryClickEvent to AxSmithing v1.6
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:535) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:235) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:216) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:180) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at com.artillexstudios.axsmithing.libs.axapi.scheduler.impl.BukkitScheduler.runLater(BukkitScheduler.java:36) ~[AxSmithing-1.6-all.jar:?]
        at com.artillexstudios.axsmithing.gui.impl.SmithingTable_V1_20.updateGui(SmithingTable_V1_20.java:228) ~[AxSmithing-1.6-all.jar:?]
        at com.artillexstudios.axsmithing.gui.impl.SmithingTable_V1_20.handleClick(SmithingTable_V1_20.java:166) ~[AxSmithing-1.6-all.jar:?]
        at com.artillexstudios.axsmithing.listener.InventoryListener.onInventoryClickEvent(InventoryListener.java:15) ~[AxSmithing-1.6-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1131.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3193) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$2(PacketUtils.java:102) ~[?:?]
        at io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:173) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1636) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegions$ConcreteRegionTickHandle.tickRegion(TickRegions.java:407) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by AverageGithub** [comment]
Now this is interesting. The plugin does support folia, but it seems like it didn't pick up that you're running folia for some reason. I will be investigating this issue, thanks for reporting!

**Comment by roggy666** [comment]
> Now this is interesting. The plugin does support folia, but it seems like it didn't pick up that you're running folia for some reason. I will be investigating this issue, thanks for reporting!

Okey, thank you!

**Comment by AverageGithub** [comment]
Fixed in 1.7!
